name: flutter_machine_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  cupertino_icons: ^1.0.2
  injectable: ^2.1.0
  equatable: ^2.0.5
  json_annotation: ^4.7.0
  dio: ^4.0.6
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.2.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.1.3
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  freezed: ^2.3.2
  bloc_test: ^9.1.0

dependency_overrides:
  test_api: 0.4.11

flutter:

  uses-material-design: true
